#!/bin/bash
import os 
import sys

def compile_python_script():
    # Retrieve the Python file name from env variable
    pyfile = os.getenv('PYFILE')

    if not pyfile:
        print(" Error: env var not set")
        sys.exit(1)

    # Ensure the specified python file exists
    if not os.path.exists(pyfile):
        print("Error: File %s does not exist" % (pyfile))
        sys.exit(1)

    # Create the output filename with a 'pyc' extension
    compiled_file = f"{os.path.splitext(pyfile)[0]}c"

    try:
        with open(pyfile, 'r') as script_file:
            script_code = script_file.read()

        # Compile the code to bytecode and write it to disk
        compiled_code = compile(script_code, pyfile, "exec")

        # Save the compiled bytecode to the output file 
        with open(compiled_file, 'wb') as compiled_file:
                compiled_file.write(compiled_code)

        print(f"Compilation successful. Compiled file saved to {compiled_file}")

    except Exception as e:
         print(f"Compilation failed: {e}")
         sys.exit(1)

if __name__ == "__main__":
     compile_python_script
